services:
  python:
    build: .
    working_dir: /app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CUSTOMER_TOKEN_THEHUNGER=${CUSTOMER_TOKEN_THEHUNGER}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
      - JUPYTER_PORT=${JUPYTER_PORT}
    restart: unless-stopped
    ports:
      - ${JUPYTER_PORT}:8888
    volumes:
      - ./app:/app
    networks:
      - default
      - shared-network
networks:
  default: 
  shared-network:
    external: true
